#!/usr/bin/env bash
# inject-secrets.sh — pull secrets from Bitwarden Secrets Manager and restart services
# Usage: BWS_ACCESS_TOKEN=<token> ./inject-secrets.sh
#    or: export BWS_ACCESS_TOKEN=<token> && ./inject-secrets.sh

set -euo pipefail

if [[ -z "${BWS_ACCESS_TOKEN:-}" ]]; then
  echo "Error: BWS_ACCESS_TOKEN is not set."
  echo "Usage: BWS_ACCESS_TOKEN=<token> ./inject-secrets.sh"
  exit 1
fi

echo "→ Pulling secrets from Bitwarden Secrets Manager..."

# Pull secrets via bws run — injects them as env vars into the subshell
eval "$(bws run -- env 2>/dev/null | grep -E '^(SUPABASE_URL|SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_JWT_SECRET|STRIPE_SECRET_KEY|STRIPE_WEBHOOK_SECRET|NOAA_TIDES_API_KEY)=' | sed 's/^/export /')"

# Verify required secrets were pulled
for var in SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY SUPABASE_JWT_SECRET; do
  if [[ -z "${!var:-}" ]]; then
    echo "Error: $var not found in bws secrets"
    exit 1
  fi
done

echo "→ Writing apps/web/.env.local..."
cat > apps/web/.env.local <<EOF
# Generated by inject-secrets.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
NEXT_PUBLIC_API_URL=http://localhost:8002
NUC_API_BASE_URL=http://api:8000
${STRIPE_SECRET_KEY:+STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}}
${STRIPE_WEBHOOK_SECRET:+STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}}
${NOAA_TIDES_API_KEY:+NOAA_TIDES_API_KEY=${NOAA_TIDES_API_KEY}}
EOF

echo "→ Writing .env (for API + docker-compose)..."
# Preserve non-secret lines from existing .env, then append updated values
grep -v -E '^(SUPABASE_URL|SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_JWT_SECRET|STRIPE_SECRET_KEY|STRIPE_WEBHOOK_SECRET|NOAA_TIDES_API_KEY)=' .env > .env.tmp 2>/dev/null || true
cat >> .env.tmp <<EOF
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
${STRIPE_SECRET_KEY:+STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}}
${STRIPE_WEBHOOK_SECRET:+STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}}
${NOAA_TIDES_API_KEY:+NOAA_TIDES_API_KEY=${NOAA_TIDES_API_KEY}}
EOF
mv .env.tmp .env

echo "→ Rebuilding + restarting api and web containers..."
docker compose up -d --build api web

echo ""
echo "✓ Done. nSwell is running."
echo "  Local:  http://localhost:3002"
echo "  HTTPS:  https://localhost:8443"
