#!/usr/bin/env bash
# inject-secrets.sh — write .env.local for the web app from the root .env, then restart services.
# Usage: ./inject-secrets.sh

set -euo pipefail

if [[ ! -f .env ]]; then
  echo "Error: .env not found. Copy .env.example and fill in your secrets."
  exit 1
fi

# Load .env
set -a; source .env; set +a

# Verify required vars are present
for var in SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
  if [[ -z "${!var:-}" ]]; then
    echo "Error: $var is not set in .env"
    exit 1
  fi
done

echo "→ Writing apps/web/.env.local..."
cat > apps/web/.env.local <<EOF
# Generated by inject-secrets.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
NEXT_PUBLIC_API_URL=http://localhost:8002
NUC_API_BASE_URL=http://api:8000
${STRIPE_SECRET_KEY:+STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}}
${STRIPE_WEBHOOK_SECRET:+STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}}
${NOAA_TIDES_API_KEY:+NOAA_TIDES_API_KEY=${NOAA_TIDES_API_KEY}}
EOF

echo "→ Rebuilding + restarting api and web containers..."
docker compose up -d --build api web

echo ""
echo "✓ Done. Koastcast is running."
echo "  Local:  http://localhost:3002"
echo "  HTTPS:  https://localhost:8443"
